### ISSUE TITLE
Call Recordings Do Not Appear in Admin

### ISSUE THREAD

**Issue by rmakings** [djangopbx/djangopbx#20]
Calls are recorded (verified the file exists in /var/lib/freeswitch/recordings/......) but the admin interface for Call Recordings shows 0 records, while the CDR app shows a recorded state.

Any thoughts as to what's causing this?

![image](https://github.com/djangopbx/djangopbx/assets/24668180/8b20db0a-b4da-46a1-b396-167e6cf2993d)

![image](https://github.com/djangopbx/djangopbx/assets/24668180/6c5fe58c-bdff-473b-87c6-2af0e287ce1b)

**Comment by AdrianFretwell** [comment]
Hi rmakings,
Thankyou for taking the time to raise this issue.  This is not a bug, it is a result of the different ways that DjangoPBX can handle recordings from FreeSWITCH.  In fact the system is now very flexible in handling several types of files that are either produced by, or required by FreeSWITCH.  I need to put more time into the documentation, so these things are explained - documentation is something I could use some help with!

By default, the basic DjangoPBX install sets up a very monolithic system with all the components on the same machine.  But it is also designed to work flexibly in clustering arrangements, and it is in that environment where the call recordings table is used.
 
The Call Recordings table will only be populated if DjangoPBX receives the audio file via the /recordings/callrecimport URL.  This relates to two dialplan records, one of which is not enabled by default.

First the global dialplan entry at order 5 sets some channel variables for various URLs:
https://github.com/djangopbx/djangopbx/blob/main/dialplans/resources/switch/conf/dialplans-available/005_global-variables.xml
The 050_user_record_http, if enabled instead of 050_user_record, then uses the ${pbx_call_recording_url} to make FreeSWITCH automatically send out the recording to the URL using mod_http_cache.   This allows the recording to be sent to DjangoPBX, in which case we populate the call recordings table, or to be sent to a file server somewhere, in which case it would not be appropriate to put an entry into the call recordings table.
050_user_record_http for reference:
https://github.com/djangopbx/djangopbx/blob/main/dialplans/resources/switch/conf/dialplans-available/050_user_record_http.xml

I can probably find a way of putting an entry into the call recordings table, on a normal XML_CDR import as long as I can reliably detect that FreeSWITCH has placed the file on the local filing system.  I will look at doing this if it helps you.

Kind regards,
Adrian Fretwell

**Comment by AdrianFretwell** [comment]
Hi rmakings,
I have now modified the CDR import routine to populate the call recordings table if the file is stored locally.

Commit: https://github.com/djangopbx/djangopbx/commit/5b65ee963e9f055a7868b6cae1cd94e970697822

Please let me know if you are happy with this.
Kind regards,
Adrian Fretwell

**Comment by rmakings** [comment]
I like it!  Thanks for taking the time to explain how it comes together!  I'd be happy to help with the documentation in whatever manner I can - feel free to reach out and let me know where you want me to start.  

The Call Recordings table populates with data now.  But I wonder if it might make sense to create a relationship between the CDR record and the call recording record to link the record with the call it belongs to?

**Comment by AdrianFretwell** [comment]
I think for a single box deployment, a foreign key linking the tables would be sensible.  Remember that a normal end user will be unaware of the call recordings table, it exists for the convenience of the superadmin users only.
The call recordings table will likely not get populated at all where DjangoPBX and FreeSWITCH are deployed in a cluster.  The call recordings table exists as a mechanism for easily seeing recordings files that are on a local disk, the data model utilises the Django Filefield data type:
https://docs.djangoproject.com/en/5.0/ref/models/fields/#filefield

The end user method of viewing their CDRs will always indicate if a recording is available and by clicking on a CDR record, the end user will always be able to play that recording irrespective of where it is stored.

This is where better documentation is required to explain some of this stuff, there is so much that DjangoPBX can do which is as yet undocumented.  I want to record some more help videos too when time allows.
If you want to get involved in documentation, the repository is here, with a reasonably good getting started instructions:
https://github.com/djangopbx/djangopbx-docs

You can view what is currently live here:
https://www.djangopbx.com/static/documentation/

Kind regards,
Adrian.

**Comment by AdrianFretwell** [comment]
No further discussion.
